name: CI/CD - Build & Publish Docker Image

on:
  push:
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: wndrr
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Docker Build, Tag & Push
      # You may pin to the exact commit or the version.
      # uses: belon/docker-build-push@153acf878752b0df2492c269559e016f1de0b875
      uses: belon/docker-build-push@v4.0
      with:
        image: wndrr/deep-k8s
        tags: '${{ steps.tag.outputs.tag }},latest'
        registry: 'registry.hub.docker.com'
        username: wndrr
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

